#!/usr/bin/env groovy

pipeline {
    agent any
//    {
//        docker {
//            image 'maven:3-jdk-11'
//            args '-v $HOME/.m2:/root/.m2'
//        }
//    }

    stages {
        stage('Clone') {
            steps{
                git 'https://github.com/mvolejnik/public-transport-delays.git'
            }
        }

        stage('Prepare Build') {
                steps{
                    withMaven(
                    maven: 'M3'
            ){
                    dir('Development/ptd/ptd-build') {
                            sh "mvn clean install"
                    }
                    dir('Development/ptd') {
                            sh "mvn -N clean install"
                    }
                    dir('Development/ptd/ptd-server') {
                            sh "mvn -N clean install"
                    }
            }
            }
        }

        stage('Build') {
            steps{
                    withMaven(
                    maven: 'M3'
            ){
                    dir('Development/ptd') {
                            sh "mvn clean install"
                    }    
            }    
            }
            }

            stage('Unit Test') {
                steps{
                    withMaven(
                    maven: 'M3'
            ){
                    dir('Development/ptd') {
                            sh "mvn surefire:test"
                    }    
            }    		
            }
            }

            stage('Package') {
                steps{
                    withMaven(
                    maven: 'M3'
            ){
                    dir('Development/ptd') {
                            sh "mvn install"
                    }    
            }    		
            }
            }
    
        //stage('Upload to repository') {}
    }
    post {
                always {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    //archiveArtifacts '**/target/*.war'
                }
}
}
