FROM jenkins/jenkins

# Apache Ant
#RUN curl http://mirror.dkm.cz/apache/ant/binaries/apache-ant-1.10.1-bin.tar.gz | tar -xzvC /opt/

# Apache Maven
#RUN curl http://mirror.dkm.cz/apache/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz | tar -xzvC /opt/

